deploy:
  common:
    project_type: rails3 | rails4 | silverstripe3 | drupal6 | drupal7 | drupal8 | php | sinatra
    base_dir: /var/www
    repository: git@gitlab.....
    project_slug: tradespot
    default_branch: master
    domain: domain.com
    user: root
    port: 22
    keep: 2
  environments:
    development:
      os:
        type: ubuntu
        version: 14.04
    staging:
      os:
        type: ubuntu
        version: 12.04
      domain: staging.domain.com
      default_branch: master
    production:
      os:
        type: ubuntu
        version: 14.04
      domain: production.domain.com
      default_branch: stable
dbs:
  default:
    development:
      name: project_development
      user: project_development
      pass:
      host: localhost
      port: 3306
    staging:
      name: project_staging
      user: project_staging
      pass: passw0rd
      host: localhost
      port: 3306
    production:
      name: project_production
      user: project_production
      pass: passw0rd
      host: localhost
      port: 3306
backup:
  local:
    keep:2
  ftp:
    keep: 10
    host: backup-host.com
    user: remote_backup
    pass: passw0rd
  sftp:
    keep: 10
    host: backup-host.com
    user: remote_backup
    pass: passw0rd
  s3:
    keep: 10
    key: key
    secret: secret
    bucket: bucket
  rsync:
    host: backup-host.com
    user: remote_backup
    pass: passw0rd
mail:
  smtp:
    development:
      default_from:
        name: dev
        email: dev@domain.com
      server: smtp.gmail.com
      domain: gmail.com
      authenticate: true
      user: username@domain.com
      pass: passw0rd
      secure: tls
      charset_encoding: utf-8
      port: 587
    staging:
      default_from:
        name: staging
        email: dev@domain.com
      server: smtp.gmail.com
      domain: gmail.com
      authenticate: true
      user: username@domain.com
      pass: passw0rd
      secure: tls
      charset_encoding: utf-8
      port: 587
    production:
      default_from:
        name: production
        email: dev@domain.com
      server: smtp.gmail.com
      domain: gmail.com
      authenticate: true
      user: username@domain.com
      pass: passw0rd
      secure: tls
      charset_encoding: utf-8
      port: 587
vhost:
  development:
    conf_path: /etc/apache2/sites-available
    type: apache
    version: 2.4
    server_name: development.domain.local
    server_aliases:
      - www.development.domain.local
    env_vars:
      RAILS_ENV: development
      APPLICATION_ENV: development
  staging:
    conf_path: /etc/apache2/sites-available
    type: apache
    version: 2.2
    server_name: staging.domain.com
    server_aliases:
      - www.staging.domain.com
    env_vars:
      RAILS_ENV: staging
      APPLICATION_ENV: staging
    basic_auth:
      -
        user: username1
        pass: passw0rd1
      -
        user: username2
        pass: passw0rd2
  production:
    conf_path: /etc/apache2/sites-available
    type: apache
    version: 2.4
    server_name: production.domain.com
    server_aliases:
      - www.production.domain.com
    server_admin: dev@domain.com
    env_vars:
      RAILS_ENV: production
      APPLICATION_ENV: production
chown:
  development:
  staging:
    -
      path: public/uploads
      user: www-data
  production:
    -
      path: public/uploads
      user: www-data
chmod:
  development:
  staging:
    -
      path: public/uploads
      mode: 775
  production:
    -
      path: public/uploads
      mode: 775
chgrp:
  development:
  staging:
    -
      path: public/uploads
      group: www-data
  production:
    -
      path: public/uploads
      group: www-data
resources:
  - public/assets
  - public/uploads
vendor:
  - vendor
  - public/thirdparty
  - public/vendor
post_cmds:
  development:
    - touch public/random_file
    - rm public/random_file
  staging:
    - touch public/random_file
    - rm public/random_file
  production:
    - touch public/random_file
    - rm public/random_file
watch:
  sass:
    -
      src:  public/themes/project/scss
      dest: public/themes/project/css
      filter: !ruby/regexp '/main\.scss$/'
    -
      src:  public/themes/project/scss
      dest: public/themes/project/css
      filter: !ruby/regexp '/typography\.scss$/'
  coffee:
    -
      src:  public/project/coffee
      dest: public/project/javascript
      filter: !ruby/regexp '/^.+\.coffee$/'
  concat_js:
    -
      onstart: true
      src:  public/project/vendor
      dest: public/project/javascript
      filter: "*"
  uglify:
    -
      src:  public/project/javascript
      dest: public/project/javascript
      filter: !ruby/regexp '/^.+(?<!min)\.js$/'
log_dirs:
  - log